include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    use_build_context_synchronously: ignore
    file_names: ignore
    use_key_in_widget_constructors: ignore
    unnecessary_string_interpolations: ignore
    sort_child_properties_last: ignore
